source 'https://rubygems.org'
ruby '2.1.5'

gem 'dotenv'
gem 'rack'
gem 'rack-recaptcha'
gem 'httparty'
gem 'sinatra'
gem 'pony'
gem 'json'
gem 'stripe'
gem 'pg'
gem 'activerecord'
gem 'sinatra-activerecord'
gem "sinatra-cross_origin", "~> 0.4.0"
